# -*- coding: utf-8 -*-
"""TASK 3(2) P.N.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFMm5xvCAokF7bzp6xCibFybaWvpK3oV
"""

def print_positive_numbers(lst):
    positives = [num for num in lst if num > 0]
    print("Output:", ", ".join(map(str, positives)))

# Sample inputs
list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

# Print positive numbers for each list
print("Input: list1 =", list1)
print_positive_numbers(list1)

print("Input: list2 =", list2)
print_positive_numbers(list2)