# -*- coding: utf-8 -*-
"""TASK Image classi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFMm5xvCAokF7bzp6xCibFybaWvpK3oV
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming your dataset is a CSV file and the target column is named 'target'
df = pd.read_csv('your_dataset.csv')

X = df.drop('target', axis=1)  # Features
y = df['target']               # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))