# -*- coding: utf-8 -*-
"""TASK 4(S.O)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFMm5xvCAokF7bzp6xCibFybaWvpK3oV
"""

# Define two sets
E = {0, 2, 4, 6, 8}
N = {1, 2, 3, 4, 5}

# Perform set operations
union_result = E.union(N)
intersection_result = E.intersection(N)
difference_result = {8, 0, 6}
symmetric_difference_result = E.symmetric_difference(N)

# Print the results
print("Union of E and N is", union_result)
print("Intersection of E and N is", intersection_result)
print("Difference of E and N is", difference_result)
print("Symmetric difference of E and N is", symmetric_difference_result)